import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1770103296652 implements MigrationInterface {
    name = 'Init1770103296652'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "attendance_month_settings" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "standard_workdays" numeric(6,2) NOT NULL, "closing_date" date, CONSTRAINT "PK_514c83b51ccc3772faa205da219" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b065ef630ddc3e104f35f6c370" ON "attendance_month_settings" ("company_id", "month", "year") `);
        await queryRunner.query(`CREATE TABLE "shift_rules" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "shift_id" integer NOT NULL, "on_time" TIME, "off_time" TIME, "on_advance_minutes" integer, "off_delay_minutes" integer, "late_minutes_as_late" integer, "late_minutes_as_lack" integer, "early_minutes_as_early" integer, "early_minutes_as_lack" integer, CONSTRAINT "REL_a699efb2eece339b84e4259cca" UNIQUE ("shift_id"), CONSTRAINT "PK_298eb2d2a1ee56af33f71a2b0a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a699efb2eece339b84e4259cca" ON "shift_rules" ("shift_id") `);
        await queryRunner.query(`CREATE TABLE "shift_rest_rules" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "shift_id" integer NOT NULL, "rest_begin_time" TIME, "rest_end_time" TIME, CONSTRAINT "PK_0ce970140559470ef7f84a69713" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_156e6b1044f24a6c9192f9e93a" ON "shift_rest_rules" ("shift_id", "rest_begin_time", "rest_end_time") `);
        await queryRunner.query(`CREATE TABLE "shift_fields" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "shift_id" integer NOT NULL, "field_name" character varying, "is_flexible" boolean NOT NULL DEFAULT false, "punch_time_number" integer, "no_need_off" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_34eecd93090edbe5ca44404c4b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94558356350e24e26fa9baae0b" ON "shift_fields" ("shift_id", "field_name") `);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "shift_name" character varying NOT NULL, CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_555c88b66687c3694b196c5b02" ON "shifts" ("company_id", "shift_name") `);
        await queryRunner.query(`CREATE TABLE "attendance_groups" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "group_name" character varying NOT NULL, "default_shift_id" integer, CONSTRAINT "PK_7240eb99fe29f6093e1cc6550e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_912027997643770c7363e28df9" ON "attendance_groups" ("company_id", "group_name") `);
        await queryRunner.query(`CREATE TABLE "job_levels" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "level_name" character varying NOT NULL, CONSTRAINT "PK_86a4e88cf87968ed4bfc349eaa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_07ef422256513f046448fdbc62" ON "job_levels" ("company_id", "level_name") `);
        await queryRunner.query(`CREATE TABLE "employee_types" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "type_name" character varying NOT NULL, CONSTRAINT "PK_bfdd4577957b57ec973469ede78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ca9cc861af38f42a93339899ed" ON "employee_types" ("company_id", "type_name") `);
        await queryRunner.query(`CREATE TABLE "employee_statuses" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "status_name" character varying NOT NULL, CONSTRAINT "PK_002adb1bf8f8e84e808e753e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6cfec6890bce2fe8dfb9c08266" ON "employee_statuses" ("company_id", "status_name") `);
        await queryRunner.query(`CREATE TABLE "attendance_methods" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "method_name" character varying NOT NULL, CONSTRAINT "PK_af7e2e948e2db133b7bf272bb08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f7ab5fa6781fcf098de4a62e48" ON "attendance_methods" ("company_id", "method_name") `);
        await queryRunner.query(`CREATE TABLE "leave_types" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "leave_type_name" character varying NOT NULL, "is_deduct_leave" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_359223e0755d19711813cd07394" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_df83f49dd79df2a2c3f189fd8f" ON "leave_types" ("company_id", "leave_type_name") `);
        await queryRunner.query(`CREATE TABLE "leave_policy_rules" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "policy_id" integer NOT NULL, "leave_type_id" integer NOT NULL, "quota_days" numeric(6,2), "is_deduct_leave" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_970f8678887600cf41f25b5d8f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c58a23a2bf708464e268ca2415" ON "leave_policy_rules" ("policy_id", "leave_type_id") `);
        await queryRunner.query(`CREATE TABLE "leave_policies" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "policy_name" character varying NOT NULL, "standard_workdays_in_policy" numeric(6,2), CONSTRAINT "PK_7d3b46bd2974cbb56e3831f3f34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_89303fbcb2f5897d84f1ccec35" ON "leave_policies" ("company_id", "policy_name") `);
        await queryRunner.query(`CREATE TABLE "attendance_daily_punches" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "daily_timesheet_id" integer NOT NULL, "punch_index" integer NOT NULL, "check_in_time" TIMESTAMP, "check_out_time" TIMESTAMP, "check_in_result" character varying, "check_out_result" character varying, "late_hours" numeric(6,2) NOT NULL DEFAULT '0', "early_hours" numeric(6,2) NOT NULL DEFAULT '0', "miss_check_in" boolean NOT NULL DEFAULT false, "miss_check_out" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_a8cb073de2ce290c5a0cda45f7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e7ca3649028e5eab9ca4ea5ea3" ON "attendance_daily_punches" ("daily_timesheet_id", "punch_index") `);
        await queryRunner.query(`CREATE TABLE "attendance_punch_records" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "employee_id" integer NOT NULL, "daily_timesheet_id" integer, "lark_record_id" character varying NOT NULL, "punch_time" TIMESTAMP NOT NULL, "punch_type" character varying, "punch_result" character varying, "source_type" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "address" character varying, "raw_payload" jsonb, CONSTRAINT "PK_b17cbce2630924639a4852b032e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f52963827865bbefb1398e754f" ON "attendance_punch_records" ("lark_record_id") `);
        await queryRunner.query(`CREATE TABLE "attendance_daily_timesheets" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "employee_id" integer NOT NULL, "attendance_date" date NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "total_workday" numeric(6,2) NOT NULL DEFAULT '0', "actual_workday" numeric(6,2) NOT NULL DEFAULT '0', "leave_value" numeric(6,2) NOT NULL DEFAULT '0', "unpaid_leave_value" numeric(6,2) NOT NULL DEFAULT '0', "business_trip_value" numeric(6,2) NOT NULL DEFAULT '0', "online_value" numeric(6,2) NOT NULL DEFAULT '0', "daily_timesheet_id" integer, CONSTRAINT "PK_4446090bbfdd6f87c70d5242242" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91c8bfaa321bf2003b5d6856bf" ON "attendance_daily_timesheets" ("employee_id", "attendance_date") `);
        await queryRunner.query(`CREATE TABLE "leave_request_items" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "request_id" integer NOT NULL, "daily_timesheet_id" integer NOT NULL, "leave_value" numeric(6,2) NOT NULL, "leave_minutes" integer NOT NULL, CONSTRAINT "PK_ffbe47ff1bcfc3fbdf7ad580c8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_476927dac4e1e3baf193a6b296" ON "leave_request_items" ("request_id", "daily_timesheet_id") `);
        await queryRunner.query(`CREATE TABLE "leave_requests" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "requester_id" integer NOT NULL, "employee_id" integer NOT NULL, "leave_type_id" integer NOT NULL, "leave_type_detail" character varying, "status" character varying NOT NULL, "submitted_at" TIMESTAMP NOT NULL, "approved_at" TIMESTAMP, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "reason" text, "leave_hours" numeric(8,2) NOT NULL, CONSTRAINT "PK_d3abcf9a16cef1450129e06fa9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92849799dc997e8bd5fa871a45" ON "leave_requests" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6515aff6283c72af00043e9cce" ON "leave_requests" ("company_id", "employee_id", "submitted_at") `);
        await queryRunner.query(`CREATE TABLE "employees" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "employee_code" character varying NOT NULL, "full_name" character varying NOT NULL, "lark_account" character varying, "email" character varying, "phone_number" character varying, "manager_id" integer, "standard_workdays" numeric(6,2), "attendance_group_id" integer, "job_level_id" integer, "employee_type_id" integer, "employee_status_id" integer, "attendance_method_id" integer, "leave_policy_id" integer, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bcdf921072a19dd2758a628c5c" ON "employees" ("manager_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed8bf314ae9f18006123e23566" ON "employees" ("company_id", "email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0fa9deb997ce66924916b89e9b" ON "employees" ("company_id", "employee_code") `);
        await queryRunner.query(`CREATE TABLE "attendance_monthly_timesheets" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "employee_id" integer NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "actual_workday_days" numeric(8,2) NOT NULL DEFAULT '0', "total_late_minutes" integer NOT NULL DEFAULT '0', "late_count" integer NOT NULL DEFAULT '0', "total_overtime_minutes" integer NOT NULL DEFAULT '0', "confirmation_status" character varying, CONSTRAINT "PK_38d591168ea59bcd8a0fbaf84c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_92e489091fca8e3433a1f6042b" ON "attendance_monthly_timesheets" ("employee_id", "company_id", "month", "year") `);
        await queryRunner.query(`CREATE TABLE "companies" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_name" character varying NOT NULL, CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_location_request_types" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "type_name" character varying NOT NULL, CONSTRAINT "PK_c145169b0e06c370dafc44ebed1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e1a6b9d546159dbfb9765eb96b" ON "work_location_request_types" ("company_id", "type_name") `);
        await queryRunner.query(`CREATE TABLE "timesheet_adjustment_types" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "adjustment_type_name" character varying NOT NULL, CONSTRAINT "PK_7807e04ac527a193077bf03cba2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_641ddaa8aaa61c0a3bd554e3d7" ON "timesheet_adjustment_types" ("company_id", "adjustment_type_name") `);
        await queryRunner.query(`CREATE TABLE "overtime_conversion_types" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "conversion_name" character varying NOT NULL, "multiplier" numeric(5,2) NOT NULL, CONSTRAINT "PK_554e4f7794fedf4369b987f55e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_30b140d328994c28940bb95afa" ON "overtime_conversion_types" ("company_id", "conversion_name") `);
        await queryRunner.query(`CREATE TABLE "work_location_request_items" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "request_id" integer NOT NULL, "daily_timesheet_id" integer NOT NULL, CONSTRAINT "PK_fa5a2014e6909128a7b80403348" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7f69b2d1aca96c0f10b751bd94" ON "work_location_request_items" ("request_id", "daily_timesheet_id") `);
        await queryRunner.query(`CREATE TABLE "work_location_requests" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "requester_id" integer NOT NULL, "request_type_id" integer NOT NULL, "status" character varying NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "location" character varying, CONSTRAINT "PK_3fb745619adf9312eec121bb549" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timesheet_adjustment_request_items" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "request_id" integer NOT NULL, "daily_timesheet_id" integer NOT NULL, "note" character varying, CONSTRAINT "PK_63ece630cb4aa9f7bdfba2047c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_db32656e1140e07e3ce3067aea" ON "timesheet_adjustment_request_items" ("request_id", "daily_timesheet_id") `);
        await queryRunner.query(`CREATE TABLE "timesheet_adjustment_requests" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "requester_id" integer NOT NULL, "adjustment_type_id" integer NOT NULL, "status" character varying NOT NULL, "date_of_error" date NOT NULL, "original_record" text, "replenishment_time" TIMESTAMP, CONSTRAINT "PK_c345a356ae30550e0fa6524a1a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "overtime_request" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "requester_id" integer NOT NULL, "shift_id" integer, "daily_timesheet_id" integer, "conversion_type_id" integer NOT NULL, "status" character varying NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "overtime_reason" text, CONSTRAINT "PK_ed27e3ef1c553fba41969ffeee5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leave_balance_transactions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "employee_id" integer NOT NULL, "leave_type_id" integer NOT NULL, "transaction_date" date NOT NULL, "change_days" numeric(8,2) NOT NULL, CONSTRAINT "PK_77a3c80c57f0e54b766aa37dde3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08749672634a88d5e48f6b6d66" ON "leave_balance_transactions" ("company_id", "employee_id", "transaction_date") `);
        await queryRunner.query(`CREATE TABLE "approval_workflow_steps" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "workflow_id" integer NOT NULL, "step_order" integer NOT NULL, "step_name" character varying, "approver_type" character varying NOT NULL, "approver_employee_id" integer, "approver_job_level_id" integer, "is_required" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_1ad180f4336345a5ad06a153be6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_83f5292586d79bd5ca2a7ef926" ON "approval_workflow_steps" ("workflow_id", "step_order") `);
        await queryRunner.query(`CREATE TABLE "approval_workflows" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "workflow_name" character varying NOT NULL, "request_module" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f326145fd927565de30b360264b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bf3f33e0a735ef539417c88921" ON "approval_workflows" ("company_id", "request_module", "workflow_name") `);
        await queryRunner.query(`CREATE TABLE "approval_logs" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" integer NOT NULL, "workflow_id" integer, "workflow_step_id" integer, "request_module" character varying NOT NULL, "request_id" bigint NOT NULL, "action" character varying NOT NULL, "action_note" text, "acted_by_employee_id" integer, "acted_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_5ea530f8eff8a9e5e143c3b60be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_446668b5b1ba368402827b0124" ON "approval_logs" ("acted_by_employee_id", "acted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e21f90c2f20ca101cd3e31958" ON "approval_logs" ("workflow_id", "workflow_step_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_55f2d06a7e500d8a6aeb084226" ON "approval_logs" ("company_id", "request_module", "request_id") `);
        await queryRunner.query(`ALTER TABLE "attendance_month_settings" ADD CONSTRAINT "FK_9c7dbd7a2b677fd4bccaf6e0dad" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_rules" ADD CONSTRAINT "FK_a699efb2eece339b84e4259cca1" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_rest_rules" ADD CONSTRAINT "FK_2fed9c0812c54848b2cd7201c2e" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_fields" ADD CONSTRAINT "FK_1304758f099d9aef3f3dcc1ae5a" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_e155f8dd2a50f91604c8d946369" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" ADD CONSTRAINT "FK_496072134ffffe2a4bcc6fb1d9d" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" ADD CONSTRAINT "FK_1bdd8eb6d4a4964b55e959f3581" FOREIGN KEY ("default_shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_levels" ADD CONSTRAINT "FK_eafba85d3dac4465dfb623edcc0" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_types" ADD CONSTRAINT "FK_aac82752e7927d632704a21e61b" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_statuses" ADD CONSTRAINT "FK_a6574c554b6e0b7493570e464d2" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_methods" ADD CONSTRAINT "FK_7cf15dacc1770dcc50c9bf2a7d2" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_types" ADD CONSTRAINT "FK_dd27cdf2939bc23d54c5a76ffee" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" ADD CONSTRAINT "FK_192cb2e4093ad9d4e9c4582dc4b" FOREIGN KEY ("policy_id") REFERENCES "leave_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" ADD CONSTRAINT "FK_3b14a2e187e55b94c01d54223f6" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_e944bd0d894099fe5632364d219" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_punches" ADD CONSTRAINT "FK_d2268f587719729593e28fc6936" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" ADD CONSTRAINT "FK_c772b416752de70012f5be0aabd" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" ADD CONSTRAINT "FK_d0057f6b04224b88d7d6ab6ae77" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" ADD CONSTRAINT "FK_df86dd872a98b3d2e84e6058821" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" ADD CONSTRAINT "FK_dd65462536c8766b20f1a2959ce" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" ADD CONSTRAINT "FK_b62ec386489f03107f0e0d4c6bf" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" ADD CONSTRAINT "FK_029a0835e26d04742ae421eda52" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_punch_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_request_items" ADD CONSTRAINT "FK_b6e9f645c6e6306227592e0b4ef" FOREIGN KEY ("request_id") REFERENCES "leave_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_request_items" ADD CONSTRAINT "FK_8b3e61ef2a493179aefd96f39b4" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_43c15abe870cf2a725b3d722b78" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_ea1ef783333d525f2a5fd0bfef4" FOREIGN KEY ("requester_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_52b4b7c7d295e204add6dbe0a09" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "FK_54a57db316598806786c2b95323" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_c5a7de0798cd028ba681bdcaf02" FOREIGN KEY ("attendance_group_id") REFERENCES "attendance_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_b1507ca50d9d279f752ceffc1c7" FOREIGN KEY ("job_level_id") REFERENCES "job_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_10586415772b6235abf83c445e3" FOREIGN KEY ("employee_type_id") REFERENCES "employee_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_d648b02390d7ce76ace5da627ff" FOREIGN KEY ("employee_status_id") REFERENCES "employee_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_caf9cd06ec683f5f1d65535f8df" FOREIGN KEY ("attendance_method_id") REFERENCES "attendance_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_0dcd192a411cb97df0e1e0b35d8" FOREIGN KEY ("leave_policy_id") REFERENCES "leave_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_7f3eeef59eece4147effe7bfa6a" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" ADD CONSTRAINT "FK_cc98cc136f67d5039838708c1bc" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" ADD CONSTRAINT "FK_7361861ffeb535b290c7bb3a2ef" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_location_request_types" ADD CONSTRAINT "FK_2c7593d035a3f979cfc757fef93" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_types" ADD CONSTRAINT "FK_3199e582053049eae2c6808c99b" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_conversion_types" ADD CONSTRAINT "FK_fe214a8da415d176d638f9250ef" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_location_request_items" ADD CONSTRAINT "FK_8450ece594213dd4d873ac6899f" FOREIGN KEY ("request_id") REFERENCES "work_location_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_location_request_items" ADD CONSTRAINT "FK_7488fc7f16173d344504c67efbd" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_location_requests" ADD CONSTRAINT "FK_ddf05c8a3d258cc6fcfec268fc2" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_location_requests" ADD CONSTRAINT "FK_b50deb9f3e0f93646208bfb6604" FOREIGN KEY ("requester_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_location_requests" ADD CONSTRAINT "FK_1ac74c3aeb00b51daf9c00f9df5" FOREIGN KEY ("request_type_id") REFERENCES "work_location_request_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_request_items" ADD CONSTRAINT "FK_68e6ec35f03c336ac812f9f5617" FOREIGN KEY ("request_id") REFERENCES "timesheet_adjustment_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_request_items" ADD CONSTRAINT "FK_5f4703033280977c510a3fe03d8" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_requests" ADD CONSTRAINT "FK_10d8443619baa37a95dc11ae6a4" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_requests" ADD CONSTRAINT "FK_d95317bf1cfb3785b89f8d86ed6" FOREIGN KEY ("requester_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_requests" ADD CONSTRAINT "FK_1efbd6c8d5248153766c070a1b6" FOREIGN KEY ("adjustment_type_id") REFERENCES "timesheet_adjustment_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_c43d531090f1733e9aa8c274ac3" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_0d08fc65fa5efd1a19c0d487046" FOREIGN KEY ("requester_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_0acd5b7e684960cc23391d23f0f" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_e7367b01b756335d022f4a30f70" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_8efc95d99066dc85d192c31efd5" FOREIGN KEY ("conversion_type_id") REFERENCES "overtime_conversion_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balance_transactions" ADD CONSTRAINT "FK_719faabb680ffc348a5b7b9a4d9" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balance_transactions" ADD CONSTRAINT "FK_8496e19a966d1942750fd1eaf3f" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_balance_transactions" ADD CONSTRAINT "FK_324a9621ef36724926700ff1c8d" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ADD CONSTRAINT "FK_d6d15be28620499e43d1c61c483" FOREIGN KEY ("workflow_id") REFERENCES "approval_workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ADD CONSTRAINT "FK_efab8b31756448bd1e7bda8907e" FOREIGN KEY ("approver_employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" ADD CONSTRAINT "FK_1a445d6c7fc10ea66768fafcc82" FOREIGN KEY ("approver_job_level_id") REFERENCES "job_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" ADD CONSTRAINT "FK_d5ad3fc5414f4d44ece331dcea6" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_logs" ADD CONSTRAINT "FK_da6f2726764391e7ae2f6cc63fc" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_logs" ADD CONSTRAINT "FK_e28bd567c9dc166c39e3be89c14" FOREIGN KEY ("acted_by_employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_logs" ADD CONSTRAINT "FK_57a8a82a4c1ecd8c6ca2b73a20c" FOREIGN KEY ("workflow_id") REFERENCES "approval_workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_logs" ADD CONSTRAINT "FK_11148c646652859d4c29b2ff17d" FOREIGN KEY ("workflow_step_id") REFERENCES "approval_workflow_steps"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "approval_logs" DROP CONSTRAINT "FK_11148c646652859d4c29b2ff17d"`);
        await queryRunner.query(`ALTER TABLE "approval_logs" DROP CONSTRAINT "FK_57a8a82a4c1ecd8c6ca2b73a20c"`);
        await queryRunner.query(`ALTER TABLE "approval_logs" DROP CONSTRAINT "FK_e28bd567c9dc166c39e3be89c14"`);
        await queryRunner.query(`ALTER TABLE "approval_logs" DROP CONSTRAINT "FK_da6f2726764391e7ae2f6cc63fc"`);
        await queryRunner.query(`ALTER TABLE "approval_workflows" DROP CONSTRAINT "FK_d5ad3fc5414f4d44ece331dcea6"`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" DROP CONSTRAINT "FK_1a445d6c7fc10ea66768fafcc82"`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" DROP CONSTRAINT "FK_efab8b31756448bd1e7bda8907e"`);
        await queryRunner.query(`ALTER TABLE "approval_workflow_steps" DROP CONSTRAINT "FK_d6d15be28620499e43d1c61c483"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_transactions" DROP CONSTRAINT "FK_324a9621ef36724926700ff1c8d"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_transactions" DROP CONSTRAINT "FK_8496e19a966d1942750fd1eaf3f"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_transactions" DROP CONSTRAINT "FK_719faabb680ffc348a5b7b9a4d9"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_8efc95d99066dc85d192c31efd5"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_e7367b01b756335d022f4a30f70"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_0acd5b7e684960cc23391d23f0f"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_0d08fc65fa5efd1a19c0d487046"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_c43d531090f1733e9aa8c274ac3"`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_requests" DROP CONSTRAINT "FK_1efbd6c8d5248153766c070a1b6"`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_requests" DROP CONSTRAINT "FK_d95317bf1cfb3785b89f8d86ed6"`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_requests" DROP CONSTRAINT "FK_10d8443619baa37a95dc11ae6a4"`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_request_items" DROP CONSTRAINT "FK_5f4703033280977c510a3fe03d8"`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_request_items" DROP CONSTRAINT "FK_68e6ec35f03c336ac812f9f5617"`);
        await queryRunner.query(`ALTER TABLE "work_location_requests" DROP CONSTRAINT "FK_1ac74c3aeb00b51daf9c00f9df5"`);
        await queryRunner.query(`ALTER TABLE "work_location_requests" DROP CONSTRAINT "FK_b50deb9f3e0f93646208bfb6604"`);
        await queryRunner.query(`ALTER TABLE "work_location_requests" DROP CONSTRAINT "FK_ddf05c8a3d258cc6fcfec268fc2"`);
        await queryRunner.query(`ALTER TABLE "work_location_request_items" DROP CONSTRAINT "FK_7488fc7f16173d344504c67efbd"`);
        await queryRunner.query(`ALTER TABLE "work_location_request_items" DROP CONSTRAINT "FK_8450ece594213dd4d873ac6899f"`);
        await queryRunner.query(`ALTER TABLE "overtime_conversion_types" DROP CONSTRAINT "FK_fe214a8da415d176d638f9250ef"`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_types" DROP CONSTRAINT "FK_3199e582053049eae2c6808c99b"`);
        await queryRunner.query(`ALTER TABLE "work_location_request_types" DROP CONSTRAINT "FK_2c7593d035a3f979cfc757fef93"`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" DROP CONSTRAINT "FK_7361861ffeb535b290c7bb3a2ef"`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" DROP CONSTRAINT "FK_cc98cc136f67d5039838708c1bc"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_7f3eeef59eece4147effe7bfa6a"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_0dcd192a411cb97df0e1e0b35d8"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_caf9cd06ec683f5f1d65535f8df"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_d648b02390d7ce76ace5da627ff"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_10586415772b6235abf83c445e3"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_b1507ca50d9d279f752ceffc1c7"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_c5a7de0798cd028ba681bdcaf02"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_54a57db316598806786c2b95323"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_52b4b7c7d295e204add6dbe0a09"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_ea1ef783333d525f2a5fd0bfef4"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "FK_43c15abe870cf2a725b3d722b78"`);
        await queryRunner.query(`ALTER TABLE "leave_request_items" DROP CONSTRAINT "FK_8b3e61ef2a493179aefd96f39b4"`);
        await queryRunner.query(`ALTER TABLE "leave_request_items" DROP CONSTRAINT "FK_b6e9f645c6e6306227592e0b4ef"`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" DROP CONSTRAINT "FK_029a0835e26d04742ae421eda52"`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" DROP CONSTRAINT "FK_b62ec386489f03107f0e0d4c6bf"`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" DROP CONSTRAINT "FK_dd65462536c8766b20f1a2959ce"`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" DROP CONSTRAINT "FK_df86dd872a98b3d2e84e6058821"`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" DROP CONSTRAINT "FK_d0057f6b04224b88d7d6ab6ae77"`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" DROP CONSTRAINT "FK_c772b416752de70012f5be0aabd"`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_punches" DROP CONSTRAINT "FK_d2268f587719729593e28fc6936"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_e944bd0d894099fe5632364d219"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" DROP CONSTRAINT "FK_3b14a2e187e55b94c01d54223f6"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" DROP CONSTRAINT "FK_192cb2e4093ad9d4e9c4582dc4b"`);
        await queryRunner.query(`ALTER TABLE "leave_types" DROP CONSTRAINT "FK_dd27cdf2939bc23d54c5a76ffee"`);
        await queryRunner.query(`ALTER TABLE "attendance_methods" DROP CONSTRAINT "FK_7cf15dacc1770dcc50c9bf2a7d2"`);
        await queryRunner.query(`ALTER TABLE "employee_statuses" DROP CONSTRAINT "FK_a6574c554b6e0b7493570e464d2"`);
        await queryRunner.query(`ALTER TABLE "employee_types" DROP CONSTRAINT "FK_aac82752e7927d632704a21e61b"`);
        await queryRunner.query(`ALTER TABLE "job_levels" DROP CONSTRAINT "FK_eafba85d3dac4465dfb623edcc0"`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" DROP CONSTRAINT "FK_1bdd8eb6d4a4964b55e959f3581"`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" DROP CONSTRAINT "FK_496072134ffffe2a4bcc6fb1d9d"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_e155f8dd2a50f91604c8d946369"`);
        await queryRunner.query(`ALTER TABLE "shift_fields" DROP CONSTRAINT "FK_1304758f099d9aef3f3dcc1ae5a"`);
        await queryRunner.query(`ALTER TABLE "shift_rest_rules" DROP CONSTRAINT "FK_2fed9c0812c54848b2cd7201c2e"`);
        await queryRunner.query(`ALTER TABLE "shift_rules" DROP CONSTRAINT "FK_a699efb2eece339b84e4259cca1"`);
        await queryRunner.query(`ALTER TABLE "attendance_month_settings" DROP CONSTRAINT "FK_9c7dbd7a2b677fd4bccaf6e0dad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55f2d06a7e500d8a6aeb084226"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e21f90c2f20ca101cd3e31958"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_446668b5b1ba368402827b0124"`);
        await queryRunner.query(`DROP TABLE "approval_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf3f33e0a735ef539417c88921"`);
        await queryRunner.query(`DROP TABLE "approval_workflows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83f5292586d79bd5ca2a7ef926"`);
        await queryRunner.query(`DROP TABLE "approval_workflow_steps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08749672634a88d5e48f6b6d66"`);
        await queryRunner.query(`DROP TABLE "leave_balance_transactions"`);
        await queryRunner.query(`DROP TABLE "overtime_request"`);
        await queryRunner.query(`DROP TABLE "timesheet_adjustment_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db32656e1140e07e3ce3067aea"`);
        await queryRunner.query(`DROP TABLE "timesheet_adjustment_request_items"`);
        await queryRunner.query(`DROP TABLE "work_location_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f69b2d1aca96c0f10b751bd94"`);
        await queryRunner.query(`DROP TABLE "work_location_request_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30b140d328994c28940bb95afa"`);
        await queryRunner.query(`DROP TABLE "overtime_conversion_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_641ddaa8aaa61c0a3bd554e3d7"`);
        await queryRunner.query(`DROP TABLE "timesheet_adjustment_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1a6b9d546159dbfb9765eb96b"`);
        await queryRunner.query(`DROP TABLE "work_location_request_types"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92e489091fca8e3433a1f6042b"`);
        await queryRunner.query(`DROP TABLE "attendance_monthly_timesheets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fa9deb997ce66924916b89e9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed8bf314ae9f18006123e23566"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcdf921072a19dd2758a628c5c"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6515aff6283c72af00043e9cce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92849799dc997e8bd5fa871a45"`);
        await queryRunner.query(`DROP TABLE "leave_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_476927dac4e1e3baf193a6b296"`);
        await queryRunner.query(`DROP TABLE "leave_request_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91c8bfaa321bf2003b5d6856bf"`);
        await queryRunner.query(`DROP TABLE "attendance_daily_timesheets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52963827865bbefb1398e754f"`);
        await queryRunner.query(`DROP TABLE "attendance_punch_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7ca3649028e5eab9ca4ea5ea3"`);
        await queryRunner.query(`DROP TABLE "attendance_daily_punches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89303fbcb2f5897d84f1ccec35"`);
        await queryRunner.query(`DROP TABLE "leave_policies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c58a23a2bf708464e268ca2415"`);
        await queryRunner.query(`DROP TABLE "leave_policy_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df83f49dd79df2a2c3f189fd8f"`);
        await queryRunner.query(`DROP TABLE "leave_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7ab5fa6781fcf098de4a62e48"`);
        await queryRunner.query(`DROP TABLE "attendance_methods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cfec6890bce2fe8dfb9c08266"`);
        await queryRunner.query(`DROP TABLE "employee_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca9cc861af38f42a93339899ed"`);
        await queryRunner.query(`DROP TABLE "employee_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07ef422256513f046448fdbc62"`);
        await queryRunner.query(`DROP TABLE "job_levels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_912027997643770c7363e28df9"`);
        await queryRunner.query(`DROP TABLE "attendance_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_555c88b66687c3694b196c5b02"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94558356350e24e26fa9baae0b"`);
        await queryRunner.query(`DROP TABLE "shift_fields"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156e6b1044f24a6c9192f9e93a"`);
        await queryRunner.query(`DROP TABLE "shift_rest_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a699efb2eece339b84e4259cca"`);
        await queryRunner.query(`DROP TABLE "shift_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b065ef630ddc3e104f35f6c370"`);
        await queryRunner.query(`DROP TABLE "attendance_month_settings"`);
    }

}
