version: '3.8'

services:
  migration:
    build:
      context: .
      target: builder
    container_name: timekeeping-migration
    network_mode: host
    env_file: .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE}
      - DATABASE_SSL_ENABLED=${DATABASE_SSL_ENABLED}
    command: yarn migration:run

  api-app:
    build:
      context: .
      target: runner
    container_name: timekeeping-api
    restart: always
    network_mode: host
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE}
      - DATABASE_SSL_ENABLED=${DATABASE_SSL_ENABLED}
      - TZ=${TZ}
    command: node dist/main
    depends_on:
      migration:
        condition: service_completed_successfully